name: PHP Linting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  php-lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP runtime
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: "none"

      - name: Lint PHP files
        id: lint
        run: |
          curl -Ls https://github.com/overtrue/phplint/releases/latest/download/phplint.phar -o /usr/local/bin/phplint
          chmod +x /usr/local/bin/phplint
          Result=$(/usr/local/bin/phplint --no-cache --no-progress -v -q --exclude=vendor --log-json)
          {
            echo "result<<EOF"
            echo -e "$Result"
            echo "EOF"
          } >> $GITHUB_OUTPUT                

      - name: Show output
        run: |
          echo -e "${{ steps.lint.outputs.result }}"
