name: PHP Linting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  php-lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint PHP files
        uses: overtrue/phplint@main
        with:
          path: .
          options: --exclude=vendor --log-json
